### ISSUE TITLE
[INPUT] 35.5 - Tech News

### ISSUE THREAD

**Issue by vinicius-vasconcelos** [betrybe/sd-0x-tech-news#10]
Bloco: 35
Dia: 5
Turma: 4

Melhoria em: Projeto

No projeto `Tech news` (e talvez outros projetos em `Python`) quando as pessoas executam os testes, é trazido uma tabela com porcentagens, que esta gerando algumas confusões. Conversei com o Cássio ele deu a sugestão de colocar uma breve explicação que isso é algo interno da Trybe, não sei faz sentido deixar isso explicito no `readme`?

Os testes podem falhar para pessoas usuárias de `Windows` por causa da abertura de arquivo. Pessoas usuárias de `Windows` tem que passar o `encoding` nas aberturas dos arquivos. Os testes falha se isso não ocorrer.

**Comment by cassiobotaro** [comment]
@vinicius-vasconcelos Removi a parte de coverage dos testes que não estava fazendo sentido.

**Comment by cassiobotaro** [comment]
Resolvido com 90a45423d105ab46360d5deec2e02749c85d4aff e 66ab5c1bc38bfc56df41e823097801d93809f298.
